### ISSUE TITLE
SnipeIT Helm installer failing out-of-the-box

### ISSUE THREAD

**Issue by vunaml** [t3n/helm-charts#118] opened 2020-11-24 08:44 UTC
Hi, I tried to install the aforementioned chart, but got a lot of bumps on the road. I hope you can clarify what did I do wrong or if that is not the case it can be a good basis to improve this the otherwise quite handy chart.

Our cluster:
- managed by rancher, docker installation v2.4.8
- kubernetes v18.8
- docker v19.3.12
- all worker nodes have 8vCPU, and 16 gigs of RAM
- for Helm installation v3.4.1 is used

First, my values.yaml: 
```
image:
  repository: snipe/snipe-it
  tag: v5.0.7
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 0.2m
    memory: 1G

config:
  snipeit:
    env: production
    debug: false
    url: "http://snipeit.mycompany.net"
    key: <some-key-to-evade-snipeit-comin-after-us>
    timezone: Europe/Berlin
    locale: en
    envConfig: 
      APP_URL: http://snipeit.mycompany.net
      MYSQL_PORT_3306_TCP_ADDR: snipeit-mysql.snipeit.svc.cluster.local
      MYSQL_PORT_3306_TCP_PORT: 3306
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: <some-secure-snipeit-password>

mysql:
  enabled: true
  mysqlUser: snipeit
  mysqlPassword: <some-secure-snipeit-password>
  mysqlDatabase: snipeit
  mysqlRootPassword: <some-secure-root-password>

  persistence:
    enabled: true
    storageClass: longhorn-retain
    accessMode: ReadWriteOnce
    size: 2Gi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: longhorn-retain
  size: 2Gi

  www:
    mountPath: /var/lib/snipeit
    subPath: www
  sessions:
    mountPath: /var/www/html/storage/framework/sessions
    subPath: sessions

ingress:
  enabled: true
  path: /
  hosts:
    - snipeit.mycompany.net
```

Any not mentioned value is left at its original value. The command I used to deploy this in its own namespace:
```helm install snipeit t3n/snipeit -f values.yaml```

After this I spent some hours to debugging, finally pinpointing down our problems to these points:
1. It may be the our PV provisioner (longhorn) but permissions on the /storage folder causing readiness checks to fail, and eventually a CrashLoopBackoff. 
For quick-and-dirty, a ```kubectl exec``` and a ```chmod -R 777``` did the trick.
2. The mysql container is v8.0, so it comes with default authentication plugin _caching\_sha2\_plugin_, which makes it impossibble to anything php-based to connect. 
After changing it for the snipeit account to _mysql\_native\_password_ the problem went away.
2b. In order to do that, you need the mysql root password, which is not documented, but can be get from a secret. Because I caould not login with that, I used the _mysqlRootPassword_ value from the t3n/mysql chart. It works beutifully, kudos for that!
3. Default db name is with hyphen. 
Probably a no-brainer for most people, but when you use mysql to modify it, it MUST be between backticks, which can be a though one for someoone just getting known helm.
4. The GUI setup died 3 times at the database setup part. 
From the logs it looks like the _oauth\_authentication\_token_ table is created twice. Strangely when ran ```php artisan migrate:fresh``` from the container, it ran without a hassle, and the GUI acknowledged the existing DB and I could finish the setup. 

Although we managed to get it up and running, I would like to get some insight how this could be evaded, or these are general and we just should fork and create a PR for these ourselves.

**Comment by mschmidt291** [comment] 2020-11-25 13:53
Hi,

I actually was not able to reproduce your problems on a fresh Minikube Instance. The only thing I noticed is, that when you don't specify a correct APP_KEY (with `docker run -i -t snipe/snipe-it php artisan key:generate --show`) the setup will error out with a 500 and thus will result in a crashloopbackoff.

But I actually would like to tackle down your problems. Are you able to set it up 1:1 as the last time, then edit the deployment and remove the liveness probes, so the container won't be restarted? Then you could curl your installer from the pod and then look at the laravel.log file in storage/logs/.
Maybe this will give us some more infos.

**Comment by mschmidt291** [comment] 2020-12-08 11:33
Closing this due to no answer.

**Closed by mschmidt291** 2020-12-08 11:33 UTC
